[package]
name = "fpr-cli"
version = "0.1.8"
authors = ["Shinji Hoshino <funny.pig.run@gmail.com>"]
description = "A library that allows one to write cli tools quickly."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/shinjitumala/fpr-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
unicode-width = "*"
inquire = "*"
