workspace = { members = ["cli-derive"] }
[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-derive = { version = "0.1.0", path = "cli-derive" }
itertools = "0.12.1"
regex = "1.10.4"
