[package]
name = "sh_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli = { version = "*", path = ".." }
regex = "1.10.4"
