[package]
name = "sh"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fpr-cli = { version = "*", path = ".." }
itertools = "0.12.1"
regex = "1.10.4"
