[lib]
proc-macro = true

[package]
name = "cli-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.20.8"
quote = "1.0.35"
syn = "2.0.57"
